name: dair-v2x
channels:
  - conda-forge
  - nvidia
  - pytorch
  - robostack-humble
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=6_kmp_llvm
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h2019614_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - apptools=5.1.0=pyh44b312d_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attr=2.5.2=h39aace5_0
  - blas=1.0=mkl
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.16.0=ha61ee94_1014
  - configobj=5.0.9=pyhd8ed1ab_0
  - cudatoolkit=11.3.1=ha36c431_9
  - curl=8.1.2=h409715c_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.2.0=h27087fc_1
  - eigen=3.4.0=h171cf75_1
  - envisage=6.0.1=pyhd8ed1ab_0
  - expat=2.7.3=hecca717_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_h3b011a4_111
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.1=py38h01eb140_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.41=h17648ed_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=70.1=h27087fc_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jpeg=9e=h0b41bf4_3
  - jsoncpp=1.9.5=h4bd325d_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_3
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=12_linux64_mkl
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.1.2=h409715c_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt=1.11.1=ha770c72_0
  - libgcrypt-devel=1.11.1=hb9d3cd8_0
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgcrypt-tools=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.80.2=hf974151_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm15=15.0.7=hadd5161_1
  - libltdl=2.4.3a=h5888daf_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.1=nompi_h34a3ff0_101
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=hd0c01bc_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.43=h2797004_0
  - libpq=15.3=hbcd7760_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=253=h8c4010b_1
  - libtasn1=4.20.0=hb03c661_1
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.5.4=h5888daf_0
  - libudev1=253=h0b41bf4_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.18.0=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=21.1.6=h4922eb0_0
  - loguru=0.7.2=py38h578d9bd_1
  - lz4-c=1.9.4=hcb278e6_0
  - mayavi=4.8.1=py38hcb4fa59_7
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-include=2024.2.2=ha770c72_17
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.0.8=py38hea7755e_0
  - multidict=6.0.5=py38h01eb140_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.5=h2d0b736_3
  - nettle=3.9.1=h7ab15ed_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nspr=4.38=h29cc59b_0
  - nss=3.100=hca3bf56_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.8=h7b32b05_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.43=hcad00b1_0
  - pillow=9.4.0=py38hde6dc18_1
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - ply=3.11=pyhd8ed1ab_2
  - proj=9.1.1=h8ffa02c_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.11.4=h59595ed_1
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pyface=8.0.0=pyhd8ed1ab_1
  - pyqt=5.15.9=py38hffdaa6c_5
  - pyqt5-sip=12.12.2=py38h17151c0_5
  - python=3.8.18=hd12c33a_0_cpython
  - python_abi=3.8=8_cp38
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - qt-main=5.15.8=h5d23da1_6
  - readline=8.2=h8c095d6_2
  - sip=6.7.12=py38h17151c0_0
  - sqlite=3.46.0=h6d4b2fc_0
  - svt-av1=1.4.1=hcb278e6_0
  - tbb=2021.7.0=h924138e_0
  - tbb-devel=2021.7.0=h924138e_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=0.10.0=py38_cu113
  - torchvision=0.11.0=py38_cu113
  - traits=6.4.3=py38h01eb140_0
  - traitsui=8.0.0=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - utfcpp=4.0.8=ha770c72_0
  - vtk=9.2.6=qt_py38h6b1c7ce_200
  - wheel=0.45.1=pyhd8ed1ab_0
  - wslink=2.2.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yarl=1.9.4=py38h01eb140_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - anyio==4.5.2
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.14.2
      - black==24.8.0
      - bleach==6.1.0
      - cachetools==5.5.2
      - ccimport==0.4.4
      - certifi==2025.11.12
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cumm-cu113==0.2.8
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - fire==0.7.1
      - flake8==7.1.2
      - fonttools==4.57.0
      - fqdn==1.5.1
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - imageio==2.35.1
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - lark==1.3.1
      - llvmlite==0.31.0
      - lyft-dataset-sdk==0.0.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.5.2
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - mmcls==0.23.2
      - mmcv-full==1.4.0
      - mmdet==2.25.1
      - mmsegmentation==0.27.0
      - model-index==0.1.11
      - mypy-extensions==1.1.0
      - narwhals==1.42.1
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==2.2
      - ninja==1.13.0
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numba==0.48.0
      - numpy==1.19.5
      - nuscenes-devkit==1.1.10
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.4.4
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pccm==0.4.16
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.5.0
      - pluggy==1.5.0
      - plyfile==1.0.3
      - portalocker==3.0.0
      - prettytable==3.11.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.52
      - protobuf==5.29.5
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pyflakes==3.2.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pypcd==0.1.1
      - pyquaternion==0.9.9
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - python-lzf==0.2.6
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.35.1
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rpds-py==0.20.1
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.3
      - setuptools==60.2.0
      - shapely==1.8.5
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - spconv-cu113==2.1.21
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tinycss2==1.2.1
      - tomli==2.3.0
      - tornado==6.4.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - trimesh==2.35.39
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.15
      - yapf==0.43.0
      - zipp==3.20.2
prefix: /home/bhargav/miniconda3/envs/dair-v2x
